# Bishop's University
## Department of Computer Science
### Programming Languages fro Data Analysis - CS405
#### Assignment 1 - Covid19 Data Analysis

## First:
1. Create a folder named **Assignement_1** in your GDrive.
2. Inside The folder **Assignement_1**, create a Python Notebook named **A1_Group_XX.ipynb**, where XX is the number of your group.
3. Load the file **time_series_covid19_confirmed_global.csv** from "CSSEGISandData" Github repository.
4. Upload it into your GDrive **Assignement_1** folder.
5. Answer the following questions.
6. Upload your **A1_Group_XX.ipynb** on Moodle.
7. Dealine: 30 Spetmeber (firm).
* Below are the results. You must provide the code in the corresponding cells that generate these results.

## 1. Mount your Google drive

## 2. Move to the  **Assignement_1** (Change directory)
- This allow you to access your csv file


# 3. Load global data from csv file

In [1]:
import pandas as pd

df = pd.read_csv('time_series_covid19_confirmed_global.csv')
df.head(3)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20,3/30/20,3/31/20,4/1/20,4/2/20
0,NaN,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,74,84,94,110,110,120,170,174,237,273
1,NaN,Albania,41.1533,20.1683,0,0,0,0,0,0,...,123,146,174,186,197,212,223,243,259,277
2,NaN,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,264,302,367,409,454,511,584,716,847,986

## 4. Count and display the total number of NaN values if any

In [2]:
# Total number of NaN values across the whole dataframe
df.isnull().sum().sum()

np.int64(178)

## 5. Replace the NaN values with the text 'not available'
- Show some rows with updated text

In [3]:
df = df.fillna('not available')
df.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20,3/30/20,3/31/20,4/1/20,4/2/20
0,not available,Afghanistan,33.0000,65.0000,0,0,0,0,0,0,...,74,84,94,110,110,120,170,174,237,273
1,not available,Albania,41.1533,20.1683,0,0,0,0,0,0,...,123,146,174,186,197,212,223,243,259,277
2,not available,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,264,302,367,409,454,511,584,716,847,986
3,not available,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,164,188,224,267,308,334,370,376,390,428
4,not available,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,3,3,4,4,5,7,7,7,8,8

# 6. Load only China's data

In [4]:
china = df[df['Country/Region'] == 'China']
china.head(3)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20,3/30/20,3/31/20,4/1/20,4/2/20
49,Anhui,China,31.8257,117.2264,1,9,15,39,60,70,...,990,990,990,990,990,990,990,990,990,990
50,Beijing,China,40.1824,116.4142,14,22,36,41,68,80,...,558,561,566,569,573,577,577,580,580,582
51,Chongqing,China,30.0572,107.8740,6,9,27,57,75,110,...,578,578,578,578,578,579,579,579,579,579

## 7. Update the index
- If the indexes dont start from 0, then reset it to start from 0.
- You may need a new dataframe.

In [5]:
china = china.reset_index(drop=True)
china.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20,3/30/20,3/31/20,4/1/20,4/2/20
0,Anhui,China,31.8257,117.2264,1,9,15,39,60,70,...,990,990,990,990,990,990,990,990,990,990
1,Beijing,China,40.1824,116.4142,14,22,36,41,68,80,...,558,561,566,569,573,577,577,580,580,582
2,Chongqing,China,30.0572,107.8740,6,9,27,57,75,110,...,578,578,578,578,578,579,579,579,579,579
3,Fujian,China,26.0789,117.9874,1,5,10,18,35,59,...,318,322,328,331,337,338,340,343,345,345
4,Gansu,China,37.8099,101.0583,0,2,2,4,7,14,...,136,136,136,136,136,138,138,138,138,138

## 8. Discard Country/region, Lat and Long columns
- Creat a new dataframe

In [6]:
china_cases = china.drop(columns=['Country/Region', 'Lat', 'Long'])
china_cases.head()

,Province/State,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,...,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20,3/30/20,3/31/20,4/1/20,4/2/20
0,Anhui,1,9,15,39,60,70,106,152,200,...,990,990,990,990,990,990,990,990,990,990
1,Beijing,14,22,36,41,68,80,91,111,114,...,558,561,566,569,573,577,577,580,580,582
2,Chongqing,6,9,27,57,75,110,132,147,182,...,578,578,578,578,578,579,579,579,579,579
3,Fujian,1,5,10,18,35,59,80,84,101,...,318,322,328,331,337,338,340,343,345,345
4,Gansu,0,2,2,4,7,14,19,24,26,...,136,136,136,136,136,138,138,138,138,138

# 9. Transpose the table. Provinces as columns and Cases as rows

In [7]:
# Provinces become the columns and the daily cases become the rows
china_t = china_cases.T
china_t.columns = china_t.iloc[0]                 # province names as column headers
china_t = china_t.drop(china_t.index[0]).reset_index(drop=True)
china_t.columns.name = None
china_t.head()

,Anhui,Beijing,Chongqing,Fujian,Gansu,Guangdong,Guangxi,Guizhou,Hainan,Hebei,...,Shaanxi,Shandong,Shanghai,Shanxi,Sichuan,Tianjin,Tibet,Xinjiang,Yunnan,Zhejiang
0,1,14,6,1,0,26,2,1,4,1,...,0,2,9,1,5,4,0,0,1,10
1,9,22,9,5,2,32,5,3,5,1,...,3,6,16,1,8,4,0,2,2,27
2,15,36,27,10,2,53,23,3,8,2,...,5,15,20,1,15,8,0,2,5,43
3,39,41,57,18,4,78,23,4,19,8,...,15,27,33,6,28,10,0,3,11,62
4,60,68,75,35,7,111,36,5,22,13,...,22,46,40,9,44,14,0,4,16,104

# 10. Data analysis
1. Display the number of cases by province during the 70 days considered

In [8]:
# Sum of the cases recorded for each province over the period
china_t.sum()

Anhui               57547
Beijing             26713
Chongqing           34445
Fujian              18269
Gansu                6646
Guangdong           81716
Guangxi             14892
Guizhou              8305
Hainan               9924
Hebei               17977
Heilongjiang        26835
Henan               74565
Hong Kong           11193
Hubei             3572897
Hunan               60437
Inner Mongolia       4548
Jiangsu             36696
Jiangxi             54546
Jilin                5385
Liaoning             7610
Macau                 971
Ningxia              4232
Qinghai              1127
Shaanxi             14676
Shandong            41325
Shanghai            22190
Shanxi               7954
Sichuan             31210
Tianjin              8088
Tibet                  64
Xinjiang             4283
Yunnan              10611
Zhejiang            73711
dtype: object

2. Describe the data

In [9]:
china_t.describe()

,Anhui,Beijing,Chongqing,Fujian,Gansu,Guangdong,Guangxi,Guizhou,Hainan,Hebei,...,Shaanxi,Shandong,Shanghai,Shanxi,Sichuan,Tianjin,Tibet,Xinjiang,Yunnan,Zhejiang
count,72,72,72,72,72,72,72,72,72,72,...,72,72,72,72,72,72,72,72,72,72
unique,33,62,37,43,32,61,34,25,26,38,...,36,48,54,28,48,41,2,27,32,51
top,990,399,576,296,91,1352,252,146,168,318,...,245,758,337,133,539,136,1,76,174,1205
freq,35,3,27,22,17,4,21,45,44,23,...,26,10,6,28,12,21,64,45,25,9